---
spring:
  datasource:
    minIdle: 1
    validationQuery: select 'x'
    initialSize: 1
    maxWait: 60000
    poolPreparedStatements: true
    filters: stat
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://119.29.230.48:3306/person?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    password: Root!!2018
    testOnBorrow: false
    maxOpenPreparedStatements: 20
    testWhileIdle: true
    minEvictableIdleTimeMillis: 300000
    timeBetweenEvictionRunsMillis: 60000
    testOnReturn: false
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 2
    username: root
  thymeleaf:
    mode: HTML5
    cache: false
    prefix: classpath:/
    servlet:
      content-type: text/html
    encoding: UTF-8
    suffix: .html
    enabled: true
#  devtools:
#    restart:
#      enabled: true
#      additional-paths: src/main/java
#mybatis:
#  configuration:
#    default-fetch-size: 100
#    default-statement-timeout: 3000
#    map-underscore-to-camel-case: true
#  mapperLocations: classpath:com/example/dao/*.xml
#  type-aliases-package: com.example.entity
mybatis-plus:
#  mapper-locations: classpath:com/example/dao/*.xml
  mapper-locations: classpath:/mappers/*Mapper.xml
  type-aliases-package: com.example.entity
  global-config:
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
redis:
  password: password
  port: 6379
  poolMaxTotal: 10
  poolMaxWait: 3
  poolMaxIdle: 10
  host: 119.29.230.48
  timeout: 3
